import { palette } from './palette'

export const theme = {
  defaultTheme: 'light',
  themes: {
    light: {
      dark: false,
      colors: {
        primary: palette.primary[500],
        'primary-darken-1': palette.primary[700],
        secondary: palette.secondary[500],
        'secondary-darken-1': palette.secondary[700],
        accent: palette.accent[500],
        'accent-darken-1': palette.accent[700],
        success: palette.success[500],
        info: palette.info[500],
        warning: palette.warning[500],
        error: palette.error[500],
        'on-primary': '#FFFFFF',
        'on-secondary': '#FFFFFF',
        'on-accent': '#FFFFFF',
        'on-success': '#FFFFFF',
        'on-info': '#FFFFFF',
        'on-warning': '#FFFFFF',
        'on-error': '#FFFFFF',
        'surface': palette.neutral[50],
        'surface-variant': palette.neutral[100],
        'on-surface': palette.neutral[900],
        'on-surface-variant': palette.neutral[700],
        'outline': palette.neutral[300],
        'outline-variant': palette.neutral[200],
        'inverse-surface': palette.neutral[900],
        'inverse-on-surface': palette.neutral[50],
        'inverse-primary': palette.primary[100],
        'shadow': palette.neutral[900],
        'scrim': palette.neutral[900],
        'backdrop': palette.neutral[900],
        'elevation-0': palette.neutral[50],
        'elevation-1': palette.neutral[100],
        'elevation-2': palette.neutral[200],
        'elevation-3': palette.neutral[300],
        'elevation-4': palette.neutral[400],
        'elevation-5': palette.neutral[500]
      }
    },
    dark: {
      dark: true,
      colors: {
        primary: palette.primary[300],
        'primary-darken-1': palette.primary[100],
        secondary: palette.secondary[300],
        'secondary-darken-1': palette.secondary[100],
        accent: palette.accent[300],
        'accent-darken-1': palette.accent[100],
        success: palette.success[300],
        info: palette.info[300],
        warning: palette.warning[300],
        error: palette.error[300],
        'on-primary': palette.neutral[900],
        'on-secondary': palette.neutral[900],
        'on-accent': palette.neutral[900],
        'on-success': palette.neutral[900],
        'on-info': palette.neutral[900],
        'on-warning': palette.neutral[900],
        'on-error': palette.neutral[900],
        'surface': palette.neutral[900],
        'surface-variant': palette.neutral[800],
        'on-surface': palette.neutral[50],
        'on-surface-variant': palette.neutral[300],
        'outline': palette.neutral[600],
        'outline-variant': palette.neutral[700],
        'inverse-surface': palette.neutral[50],
        'inverse-on-surface': palette.neutral[900],
        'inverse-primary': palette.primary[700],
        'shadow': palette.neutral[50],
        'scrim': palette.neutral[50],
        'backdrop': palette.neutral[50],
        'elevation-0': palette.neutral[900],
        'elevation-1': palette.neutral[800],
        'elevation-2': palette.neutral[700],
        'elevation-3': palette.neutral[600],
        'elevation-4': palette.neutral[500],
        'elevation-5': palette.neutral[400]
      }
    }
  }
}
